---
sudo: required

services:
  - docker

env:
  - distribution: debian
    version: jessie
  - distribution: debian
    version: wheezy
  - distribution: debian
    version: stretch
  - distribution: ubuntu
    version: trusty
  - distribution: ubuntu
    version: xenial

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=tests/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible tests'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/ansible-role-install-resilio:ro ${distribution}-${version}:ansible > "${container_id}"'
  # syntax check
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-install-resilio/tests/test.yml --syntax-check'
  # role execution
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-install-resilio/tests/test.yml'

notifications:
  # Notify Ansible Galaxy when a role builds successfully.
